# Generated by Django 4.1.1 on 2022-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hj_userprofile_delete_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.CharField(max_length=120, null=True, unique=True)),
                ('seat', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
