# Generated by Django 4.1.1 on 2022-10-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnumber',
            name='seat',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=120, null=True),
        ),
    ]
