# Generated by Django 4.1.1 on 2022-10-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_roomnumber_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.roomnumber'),
        ),
    ]
