# Generated by Django 4.1.1 on 2022-10-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ID_NO',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
