# Generated by Django 4.1.1 on 2022-10-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userprofile_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ID_NO',
            field=models.IntegerField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
