# Generated by Django 4.1.1 on 2022-10-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_userprofile_id_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Room',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ID_NO',
            field=models.IntegerField(blank=True, error_messages={'unique': 'A user with that email address already exists.'}, max_length=100, null=True, unique=True),
        ),
    ]
