# Generated by Django 4.1.1 on 2023-01-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_userprofile_room_alter_userprofile_id_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="ID_NO",
            field=models.IntegerField(
                blank=True,
                error_messages={
                    "unique": "A user with that email address already exists."
                },
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Room_No",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.roomnumber",
            ),
        ),
    ]
