# Generated by Django 4.1.1 on 2023-01-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_userprofile_id_no_alter_userprofile_room_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="Room_No",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.roomnumber",
                unique=True,
            ),
        ),
    ]
