# Generated by Django 4.1.1 on 2023-01-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_userprofile_room_no"),
    ]

    operations = [
        migrations.DeleteModel(
            name="hj",
        ),
    ]
