# Generated by Django 4.1.1 on 2023-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_delete_hj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomnumber",
            name="roomNo",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
