# Generated by Django 4.1.1 on 2023-03-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_complain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complain",
            name="registration_no",
            field=models.IntegerField(),
        ),
    ]
