# Generated by Django 4.1.1 on 2023-03-16 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_complain_registration_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="complain",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ID_NO",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
