# Generated by Django 4.1.1 on 2023-03-16 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_complain_date_alter_userprofile_id_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complain",
            name="date",
        ),
        migrations.AddField(
            model_name="complain",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="complain",
            name="is_solved",
            field=models.BooleanField(default=False),
        ),
    ]
