# Generated by Django 4.1.1 on 2023-03-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_remove_complain_date_complain_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="Batch",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Email",
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Phone",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
