# Generated by Django 4.1.1 on 2023-03-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_userprofile_batch_alter_userprofile_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notice", models.TextField(blank=True)),
                ("events", models.TextField(blank=True)),
                ("news", models.TextField(blank=True)),
            ],
        ),
    ]
