# Generated by Django 4.1.1 on 2023-03-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notice", models.CharField(max_length=255)),
            ],
        ),
    ]
